### ISSUE TITLE
Dummy question

### ISSUE THREAD

**Issue by ZlouNyan** [sergree/DolboNet#14]
Можно ли вместо токена бота добавить токен юзера чтобы шли сообщения от пользователя а не от бота?(вроде же у них токены одинаковые).. Если нет то не можете подсказать как шлифануть под это код?(я только учусь т.ч многих нюансов работы с дискордом не знаю)

**Comment by sergree** [comment]
Добрый день) Такую возможность не стал добавлять, но, да, это легко правится
Вот здесь https://github.com/sergree/DolboNet/blob/master/bot.py#L15
надо изменить на `checking_client.run(config.token, bot=False)`
И здесь https://github.com/sergree/DolboNet/blob/master/bot.py#L29
надо изменить на `main_client = MainClient(intents=intents, bot=False)`

**Comment by sergree** [comment]
В новых версиях discord.py больше не работает, селфботы перестали поддерживаться
