### ISSUE TITLE
Как обучить бота с нуля?

### ISSUE THREAD

**Issue by mrranger** [sergree/DolboNet#2]
Как обучить бота с нуля?

**Comment by sergree** [comment]
Добрый день. Такая возможность отсутствует в размещенном репозитории.

**Comment by mrranger** [comment]
Можно как то по другому обучить его?

**Comment by sergree** [comment]
Наврядли. Для обучения использовался самописный парсер серверов Discord на селфботах, применение которого запрещено Discord Terms of Service, поэтому на GitHub его нет.
