### ISSUE TITLE
'CheckingClient' object has no attribute 'logout'

### ISSUE THREAD

**Issue by AnUser1** [sergree/DolboNet#23]
При запуске бота, вылазит эта ошибка, что делать? И как можно пофиксить?
```py
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/Dolbonet/core/checking_client.py", line 13, in on_ready
    await self.logout()
AttributeError: 'CheckingClient' object has no attribute 'logout'
```

**Comment by sergree** [comment]
Исправлено в https://github.com/sergree/DolboNet/commit/9e16f154f24247967c241439a89c7040c0d13087

1) Заново скачайте код бота
2) Включите **Message Content Intent** в настройках аккаунта бота
![Message Content Intent](https://raw.githubusercontent.com/sergree/DolboNet/master/images/bx8pwm8j2njf.png)
3) Пробуйте снова
