### ISSUE TITLE
Он не работает!

### ISSUE THREAD

**Issue by QUEST1C** [sergree/DolboNet#3]
Переделывал много раз, токен подходит, бот на секунду появляется в онлаине и всё вылетает, помоги пж!

**Comment by sergree** [comment]
Какие ошибки в консоли? Скопируйте сюда

**Comment by QUEST1C** [comment]
Вот в чем проблема, он сразу же вылетает, так я может и сам бы разобрался но там около 1мс видно окно

**Comment by sergree** [comment]
Без скопированного текста ошибки помочь невозможно

**Comment by batman1986-15** [comment]
а ты в visual studio code запусти и в консоли посмотри ошибки

**Comment by QUEST1C** [comment]
![Screenshot_57](https://user-images.githubusercontent.com/64922601/81472081-498e3a80-91fe-11ea-9f93-cd5f50d628c3.png)

**Comment by QUEST1C** [comment]
Открой, зачем ты открыл?

**Comment by sergree** [comment]
Не знаю что это за ошибка, но непосредственно к боту она не относится. Нужно сделать все по инструкции https://github.com/sergree/DolboNet#windows-10-64-bit

**Comment by QUEST1C** [comment]
я несколько раз переделывал с 0

**Comment by sergree** [comment]
https://stackoverflow.com/questions/30143999/python-dll-load-failed-1-is-not-a-valid-win32-application/52483792

Нужно убедиться что битность Windows совпадает с битностью установленного Python (или Anaconda). Скорее всего 32-битный Python (или Anaconda) установлен на 64-битную ОС, что неправильно в этом случае.

**Comment by QUEST1C** [comment]
Итак, проблема такая, все программы определяют виндоус как х64, в настройках показывает что 64-ая, а питон определяет как 32 битную
![Screenshot_62](https://user-images.githubusercontent.com/64922601/81724059-6d66b000-948c-11ea-909b-9535d5311cff.png)
![Screenshot_63](https://user-images.githubusercontent.com/64922601/81724062-6dff4680-948c-11ea-820f-dd0201af6ea5.png)
