### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by koval01** [sergree/DolboNet#4]
Здравствуйте. Как синхронизировать эту нейронную сеть с Телеграмом? Дискорд меня не интересует.

**Comment by sergree** [comment]
Добрый день, такой возможности нет, т.к. словарь токенов и анализатор текста проектировались только под сущности Discord.
Код трансформера брал здесь: https://github.com/tensorflow/examples/blob/master/community/en/transformer_chatbot.ipynb
Можете попробовать привязать к Telegram самостоятельно
