### ISSUE TITLE
Собственные команды

### ISSUE THREAD

**Issue by Good1zer** [sergree/DolboNet#6]
Здравствуйте, а можно добавить своих команд этому боту? Если да, то как это сделать? Пробовал уже много раз, но он игнорирует команды. Добавлял в "core/main_client.py" с помощью "discord.ext.commands".

**Comment by sergree** [comment]
Добрый день! Добавить можно, но не через `discord.ext.commands`.

https://github.com/sergree/DolboNet/blob/master/core/main_client.py#L63

**Comment by Good1zer** [comment]
Подскажите, пожалуйста, в чем ошибка? Пытался делать по аналогии с вашей командой !temp
```
async def test(self, message):
        if message.content.startswith('!test'):
            await message.channel.send('test')
```

**Comment by Good1zer** [comment]
![image](https://user-images.githubusercontent.com/51920327/89943219-88c98e80-dc26-11ea-9482-38eb041db885.png)

**Comment by sergree** [comment]
😀

https://github.com/sergree/DolboNet/blob/master/README.md#faq

> Нейронная сеть бота лишь отражает публичные данные, на которых проходило обучение. Возможно, это тревожный звоночек о том, [что стало с нашим обществом](http://lurkmore.to/%D0%91%D1%8B%D0%B4%D0%BB%D0%BE). В любом случае, мы не хотели.

А про ошибку ничего не могу сказать, т.к. не вижу её. Судя по коду отступы пропущены или ещё что..

Как по мне: проще запустить второго бота параллельно на том же токене (а лучше на другом) и в него уже команды добавлять.

**Comment by Good1zer** [comment]
Спасибо большое за бота и за ответ! Создал нового с этим же токеном (не знал, что так можно)!
