### ISSUE TITLE
Что за хренотень?

### ISSUE THREAD

**Issue by PEKKAch4KA** [sergree/DolboNet#7]
![изображение](https://user-images.githubusercontent.com/42832573/90310137-5dc98e00-def7-11ea-9536-56816191642e.png)

**Comment by sergree** [comment]
Наверно квота LFS кончилась, нужно https://yadi.sk/d/shcawRomGx2seA закинуть в weights

**Comment by PEKKAch4KA** [comment]
Спасибо!:)
