### ISSUE TITLE
Что это?

### ISSUE THREAD

**Issue by WENDYS23337** [sergree/DolboNet#8]
Как это решить?
![unknown](https://user-images.githubusercontent.com/74834326/99884978-90e88f80-2c53-11eb-9616-19c6e661ef1c.png)

**Comment by sergree** [comment]
Добрый день
Есть инструкция по установке: https://github.com/sergree/DolboNet#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

Из скриншота видно, что у вас не установлен `tensorflow`, тоесть пропущен шаг инструкции с установкой зависимостей.

**Comment by WENDYS23337** [comment]
Хорошо, спасибо
