### ISSUE TITLE
Код не работает

### ISSUE THREAD

**Issue by Sk9TT** [sergree/DolboNet#9]
У меня 64 битная система и Python, всё должно быть нормально. Но почему-то в коде система не может найти import discord (хотя я его устанавливал), и ещё не определяет core.checking_client и core.main_client

![image](https://user-images.githubusercontent.com/70840166/104183760-43f38f00-5434-11eb-851f-e5f0049598ff.png)

**Comment by Sk9TT** [comment]
Я проверял работоспособность discord.py на своём боте, и всё работает
![Uploading image.png…]()

**Comment by Sk9TT** [comment]
Я проверял работоспособность discord.py на своём боте, и всё работает
![image](https://user-images.githubusercontent.com/70840166/104183960-8f0da200-5434-11eb-899e-5d346a4fc4f8.png)

**Comment by sergree** [comment]
Добрый день. Что-то не так с окружением в котором запускается бот. Я не смогу помочь с этим.

**Comment by Sk9TT** [comment]
> Добрый день. Что-то не так с окружением в котором запускается бот. Я не смогу помочь с этим.

Ok
